---
name: Single-Host Blue-Green Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t $DOCKER_USERNAME/my-node-app2:latest .
          docker push $DOCKER_USERNAME/my-node-app2:latest
      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to Blue environment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/my-node-app2:latest
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $USERNAME@$HOST << 'EOF'
            docker pull $DOCKER_IMAGE
            docker stop node-app-blue || true
            docker rm node-app-blue || true
            docker run -d --name node-app-blue -p 8081:3000 $DOCKER_IMAGE
          EOF
      - name: Wait for Blue to be ready
        run: sleep 30
      - name: Verify Blue deployment
        run: curl --fail http://${{ secrets.HOST }}:8081/sayHello
      - name: Switch traffic to Blue environment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: >
          echo "$SSH_PRIVATE_KEY" > private_key.pem

          chmod 600 private_key.pem

          ssh -i private_key.pem $USERNAME@$HOST << 'EOF'
            sudo sed -i 's/node-app-green:3000/node-app-blue:3000/' /etc/nginx/sites-available/default
            sudo systemctl restart nginx
          EOF
      - name: Verify traffic switch to Blue
        run: curl --fail http://${{ secrets.HOST }}/sayHello
      - name: Shut down Green environment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $USERNAME@$HOST << 'EOF'
            docker stop node-app-green || true
            docker rm node-app-green || true
          EOF
